// Locale text is kept separate from the original Russian recipe catalog.
const UI={
ru:{title:'Готовим с Васей по-быстрому',kicker:'Моя домашняя книга рецептов',intro:'Рецепты из обычных продуктов — без лишней возни. Можно открыть с телефона, найти нужное блюдо и скопировать рецепт себе.',note:'<b>Забери рецепт себе.</b> Рецепт можно скопировать в WhatsApp, Telegram или заметки, а готовую карточку — скачать на телефон или компьютер.',footer:'Книга пополняется. Ссылка остаётся той же — новые рецепты появляются в этом каталоге после обновления.',search:'Поиск: пельмени, сыр, суп, курица…',all:'Все',open:'Открыть рецепт',share:'Поделиться',close:'Закрыть',ingredients:'Что понадобится',steps:'Как готовить',tip:'Совет',copy:'Скопировать рецепт',copied:'Скопировано ✓',download:'Скачать рецепт (.txt)',original:'Карточка на русском',empty:'Ничего не нашлось. Попробуй другое слово.',loading:'Загружаю рецепты…',error:'Не удалось загрузить рецепты. Обнови страницу. Для локального просмотра открой сайт через сервер.',copyError:'Не получилось скопировать автоматически. Выдели текст рецепта и скопируй вручную.',shareCopied:'Рецепт скопирован. Можно вставить его в WhatsApp, Telegram или сообщение.',language:'Язык',cover:'Готовим вместе по-быстрому',pending:'Перевод этого рецепта пока не готов. Ниже — русский оригинал.',categories:{'Закуски':'Закуски','Ужин':'Ужин','Курица':'Курица','Супы':'Супы','Выпечка':'Выпечка','Свинина':'Свинина','Лаваш':'Лаваш','Соусы':'Соусы','Лепёшки':'Лепёшки'}},
en:{title:'Quick cooking with Vasya',kicker:'My home recipe book',intro:'Recipes made with everyday ingredients, without the fuss. Open on your phone, find a dish and copy the recipe for yourself.',note:'<b>Keep a recipe for later.</b> Copy it into WhatsApp, Telegram or your notes, or download the recipe text. Original illustrated cards are in Russian.',footer:'More recipes are added over time. The link stays the same — new recipes appear here after an update.',search:'Search: dumplings, cheese, soup, chicken…',all:'All',open:'Open recipe',share:'Share',close:'Close',ingredients:'Ingredients',steps:'Method',tip:'Tip',copy:'Copy recipe',copied:'Copied ✓',download:'Download recipe (.txt)',original:'Original card (Russian)',empty:'No recipes found. Try another word.',loading:'Loading recipes…',error:'Could not load recipes. Refresh the page. For a local preview, open the site through a server.',copyError:'Could not copy automatically. Select the recipe text and copy it manually.',shareCopied:'Recipe copied. You can paste it into WhatsApp, Telegram or a message.',language:'Language',cover:'Quick cooking together',pending:'This recipe has not been translated yet. The Russian original is shown below.',categories:{'Закуски':'Snacks','Ужин':'Dinner','Курица':'Chicken','Супы':'Soups','Выпечка':'Baking','Свинина':'Pork','Лаваш':'Lavash','Соусы':'Sauces','Лепёшки':'Flatbreads'}},
fr:{title:'Cuisine rapide avec Vassia',kicker:'Mon carnet de recettes maison',intro:'Des recettes avec des ingrédients du quotidien, sans complications. À ouvrir sur le téléphone pour trouver un plat et copier la recette.',note:'<b>Garde une recette pour plus tard.</b> Copie-la dans WhatsApp, Telegram ou tes notes, ou télécharge son texte. Les fiches illustrées originales sont en russe.',footer:'Le carnet s’enrichit. Le lien reste le même : les nouvelles recettes apparaissent ici après chaque mise à jour.',search:'Rechercher : raviolis, fromage, soupe, poulet…',all:'Tout',open:'Voir la recette',share:'Partager',close:'Fermer',ingredients:'Ingrédients',steps:'Préparation',tip:'Conseil',copy:'Copier la recette',copied:'Copié ✓',download:'Télécharger la recette (.txt)',original:'Fiche originale (russe)',empty:'Aucune recette trouvée. Essaie un autre mot.',loading:'Chargement des recettes…',error:'Impossible de charger les recettes. Actualise la page. Pour un aperçu local, ouvre le site via un serveur.',copyError:'La copie automatique a échoué. Sélectionne le texte de la recette et copie-le manuellement.',shareCopied:'Recette copiée. Tu peux la coller dans WhatsApp, Telegram ou un message.',language:'Langue',cover:'Cuisinons ensemble rapidement',pending:'Cette recette n’est pas encore traduite. L’original russe est affiché ci-dessous.',categories:{'Закуски':'Collations','Ужин':'Dîner','Курица':'Poulet','Супы':'Soupes','Выпечка':'Pâtisserie','Свинина':'Porc','Лаваш':'Lavash','Соусы':'Sauces','Лепёшки':'Galettes'}}
};
// Preserve the site's approved Russian introduction verbatim.
Object.assign(UI.ru,{title:'Готовим с Васей по‑быстрому',kicker:'Наша домашняя книга рецептов',intro:'Рецепты из обычных продуктов — без долгой возни. Можно открыть с телефона, найти нужное блюдо и скопировать рецепт себе.',note:'<b>Берите рецепты себе.</b> Рецепт можно скопировать в WhatsApp, Telegram или заметки, а готовую карточку — скачать на телефон или компьютер.',footer:'Книга пополняется. Ссылка остаётся той же — новые рецепты появляются в этом каталоге автоматически после добавления.'});
UI.en.kicker='Our home recipe book'; UI.fr.kicker='Notre carnet de recettes maison';
let RECIPES=[],TRANSLATIONS={},currentCategory='',currentRecipe=null,lang='ru';
const $=id=>document.getElementById(id),grid=$('grid'),search=$('search'),chips=$('chips');
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=k=>UI[lang][k];
function translated(r){const tr=lang==='ru'?null:TRANSLATIONS[lang]?.[r.id];return tr?{...r,...tr}:r;}
function category(c){return UI[lang].categories[c]||c;}
function normalize(s){return String(s).toLocaleLowerCase(lang).normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function renderChips(){chips.innerHTML='';['',...new Set(RECIPES.map(r=>r.category).filter(Boolean))].forEach(c=>{const b=document.createElement('button');b.className='chip'+(c===currentCategory?' active':'');b.textContent=c?category(c):t('all');b.setAttribute('aria-pressed',String(c===currentCategory));b.onclick=()=>{currentCategory=c;renderChips();render();};chips.appendChild(b);});}
function render(){const q=normalize(search.value.trim());const rows=RECIPES.filter(r=>{const v=translated(r);return (!currentCategory||r.category===currentCategory)&&(!q||normalize([v.title,category(r.category),...(v.tags||[]),...(v.ingredients||[])].join(' ')).includes(q));});grid.innerHTML=rows.length?'':`<div class="empty">${esc(t('empty'))}</div>`;rows.forEach(raw=>{const r=translated(raw),el=document.createElement('article');el.className='card';el.dataset.recipeId=raw.id;el.innerHTML=`<img src="${esc(raw.image||'assets/quick-recipes.png')}" alt="${esc(r.title)}"><div class="cardBody"><div class="badge">${esc(category(raw.category))}</div><h2>${esc(r.title)}</h2><div class="meta">${esc(r.time||'')}</div><div class="tags">${(r.tags||[]).slice(0,4).map(s=>`<span class="tag">#${esc(s)}</span>`).join('')}</div><div class="actions"><button class="primary">${esc(t('open'))}</button><button>${esc(t('share'))}</button></div></div>`;const [open,share]=el.querySelectorAll('button');open.onclick=()=>openModal(raw);share.onclick=()=>shareRecipe(raw,share);grid.appendChild(el);});}
function recipeText(raw){const r=translated(raw);return `${r.title}\n${category(raw.category)}${r.time?' · '+r.time:''}\n\n${r.description?r.description+'\n\n':''}${t('ingredients')}:\n• ${(r.ingredients||[]).join('\n• ')}\n\n${t('steps')}:\n${(r.steps||[]).map((s,i)=>`${i+1}. ${s}`).join('\n')}\n\n${r.tip?t('tip')+': '+r.tip+'\n\n':''}${t('title')}`;}
function copied(btn){const old=btn.textContent,atLang=lang;btn.textContent=t('copied');setTimeout(()=>{if(lang===atLang&&btn.isConnected)btn.textContent=old;},1600);}
async function copyRecipe(r,btn){try{await navigator.clipboard.writeText(recipeText(r));copied(btn);}catch{alert(t('copyError'));}}
async function shareRecipe(r,btn){const text=recipeText(r);if(navigator.share){try{await navigator.share({title:translated(r).title,text});return;}catch(e){if(e?.name==='AbortError')return;}}try{await navigator.clipboard.writeText(text);copied(btn);alert(t('shareCopied'));}catch{alert(t('copyError'));}}
function openModal(raw){currentRecipe=raw;const r=translated(raw);$('mImg').src=raw.image||'assets/quick-recipes.png';$('mImg').alt=r.title;$('mCat').textContent=category(raw.category);$('mTitle').textContent=r.title;$('mTime').textContent=r.time||'';$('mDesc').textContent=r.description||'';$('mIng').innerHTML=r.ingredients.map(s=>`<li>${esc(s)}</li>`).join('');$('mSteps').innerHTML=r.steps.map(s=>`<li>${esc(s)}</li>`).join('');$('mTip').innerHTML=r.tip?`<b>${esc(t('tip'))}:</b> ${esc(r.tip)}`:'';$('translationNotice').textContent=lang!=='ru'&&!TRANSLATIONS[lang]?.[raw.id]?t('pending'):'';$('originalBtn').style.display=raw.download?'block':'none';$('modal').classList.add('open');}
function closeModal(){$('modal').classList.remove('open');currentRecipe=null;}
function downloadText(){if(!currentRecipe)return;const blob=new Blob(['\ufeff'+recipeText(currentRecipe)],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${currentRecipe.id}-${lang}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function setLanguage(next){if(!UI[next])return;lang=next;try{localStorage.setItem('gotovim-language',lang);}catch{}document.documentElement.lang=lang;document.title=t('title');document.querySelector('h1').textContent=t('title');document.querySelector('.kicker').textContent=t('kicker');document.querySelector('.heroText p').textContent=t('intro');document.querySelector('.heroText .note').innerHTML=t('note');document.querySelector('.footer').textContent=t('footer');document.querySelector('.heroImg').alt=t('cover');search.placeholder=t('search');search.setAttribute('aria-label',t('search'));$('languageLabel').textContent=t('language');$('languageSelect').value=lang;$('closeBtn').textContent=t('close');$('ingredientsTitle').textContent=t('ingredients');$('stepsTitle').textContent=t('steps');$('copyBtn').textContent=t('copy');$('shareBtn').textContent=t('share');$('downloadBtn').textContent=t('download');$('originalBtn').textContent=t('original');document.querySelector('meta[name="description"]').content=t('intro');renderChips();render();if(currentRecipe)openModal(currentRecipe);}
$('languageSelect').addEventListener('change',e=>setLanguage(e.target.value));
$('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
$('closeBtn').onclick=closeModal;$('copyBtn').onclick=()=>currentRecipe&&copyRecipe(currentRecipe,$('copyBtn'));$('shareBtn').onclick=()=>currentRecipe&&shareRecipe(currentRecipe,$('shareBtn'));$('downloadBtn').onclick=downloadText;
$('originalBtn').onclick=()=>{if(!currentRecipe?.download)return;const a=document.createElement('a');a.href=currentRecipe.download;a.download=currentRecipe.downloadName||'recipe-card.png';a.click();};search.addEventListener('input',render);
async function loadRecipes(){try{const saved=localStorage.getItem('gotovim-language');if(UI[saved])lang=saved;}catch{}setLanguage(lang);grid.innerHTML=`<div class="empty">${esc(t('loading'))}</div>`;try{const [res,tr]=await Promise.all([fetch('./data/recipes.json',{cache:'no-store'}),fetch('./data/translations.json',{cache:'no-store'})]);if(!res.ok||!tr.ok)throw Error('load');RECIPES=await res.json();TRANSLATIONS=await tr.json();if(!Array.isArray(RECIPES))throw Error('format');renderChips();render();}catch{grid.innerHTML=`<div class="empty">${esc(t('error'))}</div>`;}}
loadRecipes();
